# Generated by Django 3.1 on 2021-12-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_num', models.CharField(max_length=50)),
                ('mnth', models.CharField(max_length=10)),
                ('year', models.IntegerField(max_length=10)),
                ('cvv', models.IntegerField(max_length=10)),
                ('gmail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cardpayment',
            },
        ),
    ]
