# Generated by Django 3.1 on 2021-12-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyNKSapp', '0002_cardpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='degree_id',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='institute_id',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='specialization_id',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='user',
            field=models.IntegerField(max_length=10),
        ),
    ]
